from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from agentsheriff.api.db import get_session
from agentsheriff.models.dto import (
    ArgPredicateDTO,
    PolicyCreateRequest,
    PolicyGenerationRequest,
    PolicyGenerationResponse,
    PolicyUpdateRequest,
    PolicyVersionDTO,
    RuleAction,
    StaticRuleDTO,
    ToolMatchDTO,
)
from agentsheriff.policy.store import PolicyStore
from agentsheriff.streams import hub

router = APIRouter(prefix="/v1/policies", tags=["policies"])


@router.get("", response_model=list[PolicyVersionDTO])
def list_policies(session: Session = Depends(get_session)) -> list[PolicyVersionDTO]:
    return PolicyStore(session).list_versions()


@router.post("", response_model=PolicyVersionDTO)
def create_policy(request: PolicyCreateRequest, session: Session = Depends(get_session)) -> PolicyVersionDTO:
    return PolicyStore(session).create_draft(request)


@router.post("/generate", response_model=PolicyGenerationResponse)
def generate_policy(request: PolicyGenerationRequest) -> PolicyGenerationResponse:
    rules: list[StaticRuleDTO] = []
    if "github.push_branch" in request.tool_manifest:
        rules.append(StaticRuleDTO(
            id="policy.generated.block_force_push",
            name="Block force pushes",
            tool_match=ToolMatchDTO(kind="exact", value="github.push_branch"),
            arg_predicates=[ArgPredicateDTO(path="force", operator="equals", value=True)],
            action=RuleAction.deny,
            severity_floor=90,
            reason="Force-pushes are blocked by generated starter policy.",
            user_explanation="This action rewrites git history and is blocked by policy.",
        ))
    if "gmail.send_email" in request.tool_manifest:
        rules.append(StaticRuleDTO(
            id="policy.generated.review_email_attachments",
            name="Review email attachments",
            tool_match=ToolMatchDTO(kind="exact", value="gmail.send_email"),
            arg_predicates=[ArgPredicateDTO(path="attachments", operator="exists", value=True)],
            action=RuleAction.require_approval,
            severity_floor=55,
            reason="Email attachments require review by default.",
            user_explanation="A human should review outbound attachments before sending.",
        ))
    for tool in request.tool_manifest:
        if tool.endswith(".read") or tool.endswith(".read_inbox"):
            rules.append(StaticRuleDTO(
                id=f"policy.generated.allow_{tool.replace('.', '_')}",
                name=f"Allow {tool}",
                tool_match=ToolMatchDTO(kind="exact", value=tool),
                action=RuleAction.allow,
                severity_floor=10,
                reason="Read-only tool is allowed by generated starter policy.",
            ))
    return PolicyGenerationResponse(
        intent_summary=f"Starter policy for {request.name}: {request.user_intent}",
        judge_prompt="Use the user's stated intent and prefer approval for irreversible actions.",
        static_rules=rules,
        notes=["Generated by backend fallback; Person 2 helper can replace rule quality later."],
    )


@router.get("/{policy_id}", response_model=PolicyVersionDTO)
def get_policy(policy_id: str, session: Session = Depends(get_session)) -> PolicyVersionDTO:
    policy = PolicyStore(session).get_version(policy_id)
    if policy is None:
        raise HTTPException(status_code=404, detail="Policy version not found.")
    return policy


@router.put("/{policy_id}", response_model=PolicyVersionDTO)
def update_policy(
    policy_id: str,
    request: PolicyUpdateRequest,
    session: Session = Depends(get_session),
) -> PolicyVersionDTO:
    try:
        return PolicyStore(session).update_draft(policy_id, request)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail="Policy version not found.") from exc
    except ValueError as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc


@router.post("/{policy_id}/publish", response_model=PolicyVersionDTO)
def publish_policy(policy_id: str, session: Session = Depends(get_session)) -> PolicyVersionDTO:
    try:
        policy = PolicyStore(session).publish(policy_id)
        hub.broadcast_nowait({"type": "policy_published", "payload": policy.model_dump(mode="json")})
        return policy
    except KeyError as exc:
        raise HTTPException(status_code=404, detail="Policy version not found.") from exc
    except ValueError as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc


@router.post("/{policy_id}/archive", response_model=PolicyVersionDTO)
def archive_policy(policy_id: str, session: Session = Depends(get_session)) -> PolicyVersionDTO:
    try:
        return PolicyStore(session).archive(policy_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail="Policy version not found.") from exc
